# Generated by Django 3.1.2 on 2020-10-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('catagory', models.CharField(blank=True, default='', max_length=200)),
                ('played', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
